branch-defaults:
  master:
    environment: leixiaoyu-dev
global:
  application_name: leixiaoyu
  default_ec2_keyname: HomepageKey
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
